name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd ~/apps/apc-vote-01
          git pull origin main

      - name: Build and restart
        run: |
          cd ~/apps/apc-vote-01
          docker compose build --no-cache
          docker compose up -d
